# -*- coding: utf-8 -*-
"""spam_mail_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSQCiU21_iI3rwsgPsbYSBtfeEcbm5DF
"""

#importing libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

#loading dataset
dataset=pd.read_csv('/content/drive/MyDrive/ML_PROJECTS/SPAM_MAIL_DETECTION/mail_data.csv')

print(dataset)

print(dataset.isnull())

#replacing the null values with null string
mail_data=dataset.where((pd.notnull(dataset)),'')

#first five rows of the dataset
print(mail_data.head())

#no. of rows and columns of the dataset
print(mail_data.shape)

#label spam as 0 and ham=1
mail_data.loc[mail_data['Category']=='spam','Category']=0
mail_data.loc[mail_data['Category']=='ham','Category']=1

#seperating the data as text and labels
X=mail_data['Message']
Y=mail_data['Category']
#x is text and y are outputs

print(X)

print(Y)

#splitting the data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=3)

print(X.shape)
print(X_train.shape)
print(X_test.shape)

#feature extraction
feature_extraction=TfidfVectorizer(min_df=1,stop_words='english', lowercase=True)

X_train_features=feature_extraction.fit_transform(X_train)
X_test_features=feature_extraction.transform(X_test)

#converting Y values as integer

Y_train=Y_train.astype('int')
Y_test=Y_test.astype('int')

print(X_train)

print(X_train_features)

#training the model
model=LogisticRegression()

#traning the data with logistic regression
model.fit(X_train_features,Y_train)

#evaluating the training model
prediction_on_training_data=model.predict(X_train_features)
accuracy_on_traning_data=accuracy_score(Y_train,prediction_on_training_data)

print("accuracy on traning data : ",accuracy_on_traning_data)

#evaluating the testing  model
prediction_on_testing_data=model.predict(X_test_features)
accuracy_on_testing_data=accuracy_score(Y_test,prediction_on_testing_data)

print("accuracy on testing data : ",accuracy_on_testing_data)

precision = precision_score(Y_test, prediction_on_testing_data)
recall = recall_score(Y_test, prediction_on_testing_data)
f1 = f1_score(Y_test, prediction_on_testing_data)
cm = confusion_matrix(Y_test, prediction_on_testing_data)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:\n", cm)

#building a predictive system
input_mail=["As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune"]
#convert text into feature vector
input_data_features=feature_extraction.transform(input_mail)

#making prediction
prediction=model.predict(input_data_features)
print(prediction)

if prediction[0]==1:
  print("HAM MAIL")
else:
  print("SPAM MAIL")

"""Comparing Naive Bayes vs Logistic Regression"""

from sklearn.naive_bayes import MultinomialNB

#Train Naive Bayes model
nb_model = MultinomialNB()
nb_model.fit(X_train_features, Y_train)

nb_predictions = nb_model.predict(X_test_features)

#Evaluate Naive Bayes
nb_accuracy = accuracy_score(Y_test, nb_predictions)
nb_precision = precision_score(Y_test, nb_predictions)
nb_recall = recall_score(Y_test, nb_predictions)
nb_f1 = f1_score(Y_test, nb_predictions)

print("Naive Bayes Results")
print("Accuracy:", nb_accuracy)
print("Precision:", nb_precision)
print("Recall:", nb_recall)
print("F1:", nb_f1)

